# Generated by Django 2.1.3 on 2019-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'article")),
                ('article', models.TextField(blank=True, null=True, verbose_name="Ecrire l'article")),
            ],
        ),
    ]
